import json
import os
from pathlib import Path

import pytest

# The Flask app (via cti_transmute.default) requires TRANSMUTE_HOME at import time.
# Set it for the test session so the `client` fixture can import the app; the
# Flask-free converter tests never trigger this path.
os.environ.setdefault(
    "TRANSMUTE_HOME", str(Path(__file__).resolve().parent.parent)
)

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def misp_event() -> dict:
    """A minimal but valid MISP event, as a parsed dict."""
    return json.loads((FIXTURES / "misp_event.json").read_text())


@pytest.fixture
def stix_bundle() -> dict:
    """A minimal STIX 2.1 bundle, as a parsed dict.

    Generated by running MispToStix on the `misp_event` fixture, so it
    round-trips back to MISP through StixToMisp.
    """
    return json.loads((FIXTURES / "stix_bundle.json").read_text())


@pytest.fixture
def client():
    """Flask test client with the API blueprint mounted.

    Imported lazily so the Flask-free converter tests never pull in the app.
    """
    from website.api import api_blueprint
    from website.web import application

    application.config["TESTING"] = True
    if "transmute_api" not in application.blueprints:
        with application.app_context():
            application.register_blueprint(api_blueprint)
    return application.test_client()
