import json
import os
from pathlib import Path

import pytest

# The Flask app (via cti_transmute.default) requires TRANSMUTE_HOME at import time.
# Set it for the test session so the `client` fixture can import the app; the
# Flask-free converter tests never trigger this path.
os.environ.setdefault(
    "TRANSMUTE_HOME", str(Path(__file__).resolve().parent.parent)
)

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def misp_event() -> dict:
    """A minimal but valid MISP event, as a parsed dict."""
    return json.loads((FIXTURES / "misp_event.json").read_text())


@pytest.fixture
def stix_bundle() -> dict:
    """A minimal STIX 2.1 bundle, as a parsed dict.

    Generated by running MispToStix on the `misp_event` fixture, so it
    round-trips back to MISP through StixToMisp.
    """
    return json.loads((FIXTURES / "stix_bundle.json").read_text())


@pytest.fixture
def client():
    """Flask test client with the API blueprint mounted.

    Imported lazily so the Flask-free converter tests never pull in the app.
    """
    from website.api import api_blueprint
    from website.web import application

    application.config["TESTING"] = True
    if "transmute_api" not in application.blueprints:
        with application.app_context():
            application.register_blueprint(api_blueprint)
    return application.test_client()


@pytest.fixture
def app_db():
    """Function-scoped, SQLite-backed app context for persistence/use-case tests.

    Points the app at in-memory SQLite and creates the schema, so the use-case
    exercises the real ORM/session/transaction without a live Postgres.
    """
    from website.web import application, db
    import website.db_class.db  # noqa: F401  -- register models on db.metadata before create_all

    application.config["TESTING"] = True
    application.config["SQLALCHEMY_DATABASE_URI"] = "sqlite://"
    # The app was initialised with the Postgres URI at import; re-init so the
    # SQLite URI builds a fresh in-memory engine (flask-sqlalchemy applies the
    # StaticPool that keeps an in-memory DB alive for the session). flask-sqlalchemy
    # supports re-init (it disposes old engines); the only blocker is Flask's guard
    # against registering setup methods once a request has been served (the `client`
    # fixture may have served one), so clear that flag for the re-init.
    db._app_engines.pop(application, None)
    application.extensions.pop("sqlalchemy", None)
    application._got_first_request = False
    db.init_app(application)
    with application.app_context():
        db.create_all()
        try:
            yield db
        finally:
            db.session.remove()
            db.drop_all()
