"""initial

Revision ID: 932b4d5a18d0
Revises: 
Create Date: 2025-11-25 07:35:41.948968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '932b4d5a18d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_admin'))
        batch_op.drop_index(batch_op.f('ix_user_api_key'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_is_connected'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))

    op.drop_table('user')
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_created_at'))
        batch_op.drop_index(batch_op.f('ix_convert_public'))
        batch_op.drop_index(batch_op.f('ix_convert_updated_at'))
        batch_op.drop_index(batch_op.f('ix_convert_uuid'))

    op.drop_table('convert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('conversion_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('input_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('output_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('convert_pkey')),
    sa.UniqueConstraint('name', name=op.f('convert_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convert_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_public'), ['public'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_created_at'), ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=165), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('is_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_connected'), ['is_connected'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_admin'), ['admin'], unique=False)

    # ### end Alembic commands ###
