"""add convert_favorite table

Revision ID: 08cac0fef09f
Revises: b2e4f1a9c035
Create Date: 2026-05-29 10:43:01.757577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cac0fef09f'
down_revision = 'b2e4f1a9c035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convert_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('convert_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convert_id'], ['convert.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'convert_id', name='uq_favorite_user_convert')
    )
    with op.batch_alter_table('convert_favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convert_favorite_convert_id'), ['convert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_favorite_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convert_favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_favorite_user_id'))
        batch_op.drop_index(batch_op.f('ix_convert_favorite_convert_id'))

    op.drop_table('convert_favorite')
    # ### end Alembic commands ###
