"""add system_log table

Revision ID: 0c2789533064
Revises: a031e3203cd4
Create Date: 2026-05-14 13:14:06.000714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2789533064'
down_revision = 'a031e3203cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_system_log_created_at'))

    op.drop_table('system_log')
    # ### end Alembic commands ###
