"""add_convert_tag_association

Revision ID: 12ae3302a9f7
Revises: de9d8ad4064a
Create Date: 2026-05-20 14:17:12.899958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ae3302a9f7'
down_revision = 'de9d8ad4064a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convert_tag_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('convert_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convert_id'], ['convert.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convert_tag_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convert_tag_association_convert_id'), ['convert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_tag_association_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_tag_association_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convert_tag_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_tag_association_uuid'))
        batch_op.drop_index(batch_op.f('ix_convert_tag_association_tag_id'))
        batch_op.drop_index(batch_op.f('ix_convert_tag_association_convert_id'))

    op.drop_table('convert_tag_association')
    # ### end Alembic commands ###
