"""empty message

Revision ID: a4ecea6f4ec3
Revises: 
Create Date: 2025-11-25 09:31:57.638549

"""
from alembic import op
import sqlalchemy as sa

from website.web.utils import generate_api_key


# revision identifiers, used by Alembic.
revision = 'a4ecea6f4ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_key', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_convert_share_key'), ['share_key'], unique=False)

    convert_table = sa.table(
        'convert',
        sa.column('id', sa.Integer),
        sa.column('share_key', sa.String(36))
    )
    conn = op.get_bind()
    
    results = conn.execute(sa.select(convert_table.c.id)).fetchall()
    for row in results:
        conn.execute(
            convert_table.update()
            .where(convert_table.c.id == row.id)
            .values(share_key=generate_api_key(36))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_share_key'))
        batch_op.drop_column('share_key')

    # ### end Alembic commands ###
