"""add is_active and deleted_at to convert

Revision ID: be0b275f8264
Revises: 0c2789533064
Create Date: 2026-05-18 09:25:12.178721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0b275f8264'
down_revision = '0c2789533064'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_convert_is_active'), ['is_active'], unique=False)

    # Backfill existing rows so the filter is_active==True doesn't hide them
    op.execute("UPDATE convert SET is_active = TRUE WHERE is_active IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_is_active'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
