"""empty message

Revision ID: d7053174c298
Revises: a4ecea6f4ec3
Create Date: 2025-11-26 10:12:07.474094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7053174c298'
down_revision = 'a4ecea6f4ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('convert_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('old_output_text', sa.Text(), nullable=True),
    sa.Column('new_output_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['convert_id'], ['convert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convert_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convert_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_history_public'), ['public'], unique=False)
        batch_op.create_index(batch_op.f('ix_convert_history_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convert_history_uuid'))
        batch_op.drop_index(batch_op.f('ix_convert_history_public'))
        batch_op.drop_index(batch_op.f('ix_convert_history_created_at'))

    op.drop_table('convert_history')
    # ### end Alembic commands ###
